apiVersion: v1
kind: Pod
metadata:
  name: go-lr1-pod
  labels:
    app: go-lr1
    lab: lab2
spec:
  containers:
    - name: go-lr1
      image: ghcr.io/nightfury2283/containers-lab-1/app:sha-c94b5e6
      ports:
        - containerPort: 8080
      env:
        - name: DB_HOST
          value: "localhost"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "secret"
        - name: DB_NAME
          value: "myapp"
  imagePullSecrets:
    - name: ghcr-secret